"""added entry_id column to review model

Revision ID: e257c1a988d7
Revises: 3722a3f58775
Create Date: 2023-07-14 18:58:58.471248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e257c1a988d7'
down_revision = '3722a3f58775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews') as batch_op:
        batch_op.add_column(sa.Column('entry_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_review_entry_id', 'entries', ['entry_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews') as batch_op:
        batch_op.drop_constraint('fk_review_entry_id', type_='foreignkey')
        batch_op.drop_column('entry_id')

    # ### end Alembic commands ###
