from .db import db, environment, SCHEMA, add_prefix_for_prod
from enum import Enum

class System(Enum):
    _32X = "32X"
    _3DO = "3DO"
    AcornArchimedes = "AcornArchimedes"
    AcornElectron = "AcornElectron"
    ActionMax = 'ActionMax'
    AmazonLuna = 'AmazonLuna'
    Amiga = 'Amiga'
    AmigaCD32 = 'AmigaCD32'
    AmstradCPC = 'AmstradCPC'
    AmstradGX4000 = 'AmstradGX4000'
    Android = 'Android'
    APFM1000 = 'APF-M1000'
    AppleII = 'AppleII'
    AppleArcade = 'AppleArcade'
    AppleBandaiPippin = 'AppleBandaiPippin'
    Arcade = 'Arcade'
    Arduboy = 'Arduboy'
    Atari2600 = 'Atari2600'
    Atari5200 = 'Atari5200'
    Atari7800 = 'Atari7800'
    AtariST = 'AtariST'
    BallyAstrocade = 'BallyAstrocade'
    BattleNet = 'BattleNet'
    BBCMicro = 'BBCMicro'
    Beamdog = 'Beamdog'
    BethesdaLauncher = 'BethesdaLauncher'
    BigFishGames = 'BigFishGames'
    Blacknut = 'Blacknut'
    Browser = 'Browser'
    CasioLoopy = 'CasioLoopy'
    CasioPV1000 = 'CasioPV1000'
    Calculator = 'Calculator'
    CDi = 'CDi'
    CD32X = 'CD32X'
    ColecoAdam = 'ColecoAdam'
    ColecoVision = 'ColecoVision'
    Commodore64 = 'Commodore64'
    CommodoreCDTV = 'CommodoreCDTV'
    CommodorePlus4 = 'CommodorePlus4'
    CommodoreVIC20 = 'CommodoreVIC20'
    CougarBoy = 'CougarBoy'
    Desure = 'Desure'
    Discord = 'Discord'
    DOS = 'DOS'
    DotEmu = 'DotEmu'
    Dragon3264 = 'Dragon3264'
    Dreamcast = 'Dreamcast'
    DSiWare = 'DSiWare'
    EaAccess = 'EaAccess'
    EmersonArcadia2001 = 'EmersonArcadia2001'
    EntexAdeventureVision = 'EntexAdeventureVision'
    EpicGamesLauncher = 'EpicGamesLauncher'
    EpochSuperCassetteVision = 'EpochSuperCassetteVision'
    Evercade = 'Evercade'
    FairchildChannelF = 'FairchildChannelF'
    FamilyComputer = 'FamilyComputer'
    FamicomDiskSystem = 'FamicomDiskSystem'
    FMTowns = 'FMTowns'
    FujitsuMicro7 = 'FujitsuMicro7'
    Gamate = 'Gamate'
    GameAndWatch = 'GameAndWatch'
    GameGear = 'GameGear'
    GameBoy = 'GameBoy'
    GameBoyColor = 'GameBoyColor'
    GameBodyAdvance = 'GameBodyAdvance'
    eReader = 'eReader'
    GameWaveFamilyEntertainmentSystem = 'GameWaveFamilyEntertainmentSystem'
    GameCube = 'GameCube'
    GameFly = 'GameFly'
    GamersGate = 'GamersGate'
    GameStopPC = 'GameStopPC'
    GamesForWindows = 'GamesForWindows'
    Gamecom = 'Gamecom'
    GenesisMegaDrive = 'GenesisMegaDrive'
    GetGames = 'GetGames'
    Gizmondo = 'Gizmondo'
    GOGcom = 'GOGcom'
    GoogleStadia = 'GoogleStadia'
    GP2xWiz = 'GP2xWiz'
    GreenManGaming = 'GreenManGaming'
    HTCVive = 'HTCVive'
    HumbleBundleStore = 'HumbleBundleStore'
    HyperScan = 'HyperScan'
    IndieCity = 'IndieCity'
    IndieGala = 'IndieGala'
    Intellivision = 'Intellivision'
    IntellivisionAmico = 'IntellivisionAmico'
    iOS = 'iOS'
    iPad = 'iPad'
    iPod = 'iPod'
    iPhone = 'iPhone'
    iQuePlayer = 'iQuePlayer'
    itch_io = 'itch_io'
    Jaguar = 'Jaguar'
    JaguarCD = 'JaguarCD'
    LaserActive = 'LaserActive'
    Linux = 'Linux'
    Lynx = 'Lynx'
    Mac = 'Mac'
    MagnavoxOdyssey = 'MagnavoxOdyssey'
    MasterSystem = 'MasterSystem'
    Microvision = 'Microvision'
    Miscellaneous = 'Miscellaneous'
    Mobile = 'Mobile'
    MSX = 'MSX'
    NGage = 'NGage'
    NECPC6001 = 'NECPC6001'
    NECPC6601 = 'NECPC6601'
    NECPC8001 = 'NECPC8001'
    NECPC8801 = 'NECPC8801'
    NECPC9801 = 'NECPC9801'
    NeoGeo = 'NeoGeo'
    NeoGeoCD = 'NeoGeoCD'
    NeoGeoPocketColor = 'NeoGeoPocketColor'
    Nintendo3DS = 'Nintendo3DS'
    _3DSDownloads = '_3DSDownloads'
    NintendoDS = 'NintendoDS'
    Nintendo64 = 'Nintendo64'
    Nintendo64DD = 'Nintendo64DD'
    NintendoEntertainmentSystem = 'NintendoEntertainmentSystem'
    NintendoSwitch = 'NintendoSwitch'
    SwitchDownloads = 'SwitchDownloads'
    Nuon = 'Nuon'
    Nuuvem = 'Nuuvem'
    OculusStore = 'OculusStore'
    Odyssey2Videopac = 'Odyssey2Videopac'
    OnLive = 'OnLive'
    Origin = 'Origin'
    OUYA = 'OUYA'
    Pandora = 'Pandora'
    PC = 'PC'
    PICO8 = 'PICO8'
    Pinball = 'Pinball'
    Plato = 'Plato'
    Playdate = 'Playdate'
    Playdia = 'Playdia'
    PlayStation = 'PlayStation'
    PlayStation2 = 'PlayStation2'
    PlayStation3 = 'PlayStation3'
    PlayStation4 = 'PlayStation4'
    PlayStation5 = 'PlayStation5'
    PlayStationMobile = 'PlayStationMobile'
    PlayStationNetwork = 'PlayStationNetwork'
    PlayStationNow = 'PlayStationNow'
    PSOneClassics = 'PSOneClassics'
    PS2Classics = 'PS2Classics'
    PlayStationminis = 'PlayStationminis'
    PlayStationPortable = 'PlayStationPortable'
    PlayStationVita = 'PlayStationVita'
    PlayStationVR = 'PlayStationVR'
    PlayStationVR2 = 'PlayStationVR2'
    PlugandPlay = 'PlugandPlay'
    PocketStation = 'PocketStation'
    PokémonMini = 'PokémonMini'
    RZone = 'RZone'
    RCAStudioII = 'RCAStudioII'
    RockstarGamesLauncher = 'RockstarGamesLauncher'
    SuperACan = 'SuperACan'
    SAMCoupé = 'SAMCoupé'
    Saturn = 'Saturn'
    SegaCD = 'SegaCD'
    SegaPico = 'SegaPico'
    SegaSG1000 = 'SegaSG1000'
    SHARPMZ1500 = 'SHARPMZ1500'
    SharpX1 = 'SharpX1'
    SharpX68000 = 'SharpX68000'
    StarpathSupercharger = 'StarpathSupercharger'
    Steam = 'Steam'
    SuperNintendoEntertainmentSystem = 'SuperNintendoEntertainmentSystem'
    SuperGrafx = 'SuperGrafx'
    TapwaveZodiac = 'TapwaveZodiac'
    ThomasMO5 = 'ThomasMO5'
    TI994A = 'TI994A'
    TigerHandhelds = 'TigerHandhelds'
    TurboDuO = 'TurboDuO'
    TurboGrafx16 = 'TurboGrafx16'
    TurboGrafxCD = 'TurboGrafxCD'
    TRS80ColorComputer = 'TRS80ColorComputer'
    PrimeGaming = 'PrimeGaming'
    Uplay = 'Uplay'
    Vectrex = 'Vectrex'
    VirtualBoy = 'VirtualBoy'
    VirtualConsoleWii = 'VirtualConsoleWii'
    VirtualConsole3DS = 'VirtualConsole3DS'
    WASM4 = 'WASM4'
    WataraSupervision = 'WataraSupervision'
    Wii = 'Wii'
    WiiWare = 'WiiWare'
    WiiU = 'WiiU'
    WiiUDownloads = 'WiiUDownloads'
    VirtualConsoleWiiU = 'VirtualConsoleWiiU'
    WindowsPhone7 = 'WindowsPhone7'
    WindowsStore = 'WindowsStore'
    WonderSwanColor = 'WonderSwanColor'
    XaviXPORT = 'XaviXPORT'
    Xbox = 'Xbox'
    Xbox360 = 'Xbox360'
    XboxGamePass = 'XboxGamePass'
    XboxLIVEArcade = 'XboxLIVEArcade'
    XNAIndieGames = 'XNAIndieGames'
    Xbox360GamesonDemand = 'Xbox360GamesonDemand'
    XboxOne = 'XboxOne'
    XboxOneDownloads = 'XboxOneDownloads'
    XboxSeriesX = 'XboxSeriesX'
    Zeebo = 'Zeebo'
    Zune = 'Zune'
    ZX_Spectrum = 'ZX_Spectrum'
    ZX_SpectrumNext = 'ZX_SpectrumNext'







class Region(Enum):
    NAM = 'NAM'
    JP= 'JP'
    PAL = 'PAL'
    CN = 'CN'
    KR= 'KR'
    BR = 'BR'
    OTHER = 'Other'

class Game(db.Model):
    __tablename__ = 'games'

    if environment == 'production':
        __table_args__ = {'schema': SCHEMA}

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    system = db.Column(db.Enum(System), nullable=False)
    region = db.Column(db.Enum(Region), nullable=False)

    #Relationships
    entries = db.relationship('Entry', back_populates='game_entries', cascade='all, delete-orphan')
    reviews = db.relationship('Review', back_populates='game_reviews', cascade='all, delete-orphan')




    def to_dict(self):
        return {
            'id': self.id,
            'name': self.name,
            'system': self.system.value,
            'region': self.region.value
        }
