from .db import db, environment, SCHEMA, add_prefix_for_prod
from enum import Enum

class System(Enum):
    _32X = "32X"
    _3DO = "3DO"
    Acorn_Archimedes = "Acorn Archimedes"
    Acorn_Electron = "Acorn Electron"
    Action_Max = 'Action Max'
    Amazon_Luna = 'Amazon Luna'
    Amiga = 'Amiga'
    Amiga_CD32 = 'Amiga CD32'
    Amstrad_CPC = 'Amstrad CPC'
    Amstrad_GX4000 = 'Amstrad GX4000'
    Android = 'Android'
    APF_M1000 = 'APF-M1000'
    Apple_II = 'Apple II'
    Apple_Arcade = 'Apple Arcade'
    Apple_Bandai_Pippin = 'Apple Bandai Pippin'
    Arcade = 'Arcade'
    Arduboy = 'Arduboy'
    Atari_2600 = 'Atari 2600'
    Atari_5200 = 'Atari 5200'
    Atari_7800 = 'Atari 7800'
    Atari_ST = 'Atari ST'
    Bally_Astrocade = 'Bally Astrocade'
    Battle_Net = 'Battle.net'
    BBC_Micro = 'BBC Micro'
    Beamdog = 'Beamdog'
    Bethesda_Launcher = 'Bethesda Launcher'
    Big_Fish_Games = 'Big Fish Games'
    Blacknut = 'Blacknut'
    Browser = 'Browser'
    Casio_Loopy = 'Casio Loopy'
    Casio_PV_1000 = 'Casio PV-1000'
    Calculator = 'Calculator'
    CD_i = 'CD-i'
    CD32X = 'CD32X'
    Coleco_Adam = 'Coleco Adam'
    ColecoVision = 'ColecoVision'
    Commodore_64 = 'Commodore 64'
    Commodore_CDTV = 'Commodore CDTV'
    Commodore_Plus4 = 'Commodore Plus4'
    Commodore_VIC_20 = 'Commodore VIC-20'
    Cougar_Boy = 'Cougar Boy'
    Desure = 'Desura'
    Discord = 'Discord'
    DOS = 'DOS'
    DotEmu = 'DotEmu'
    Dragon_32_64 = 'Dragon 32/64'
    Dreamcast = 'Dreamcast'
    DSiWare = 'DSiWare'
    Ea_Access = 'Ea Access'
    Emerson_Arcadia_2001 = 'Emerson Arcadia 2001'
    Entex_Adeventure_Vision = 'Entex Adventure Vision'
    Epic_Games_Launcher = 'Epic Games Launcher'
    Epoch_Super_Cassette_Vision = 'Epoch Super Cassette Vision'
    Evercade = 'Evercade'
    Fairchild_Channel_F = 'Fairchild Channel F'
    Family_Computer = 'Family Computer'
    Famicom_Disk_System = 'Famicom Disk System'
    FM_Towns = 'FM Towns'
    Fujitsu_Micro_7 = 'Fujitsu Micro 7'
    Gamate = 'Gamate'
    Game_And_Watch = 'Game And Watch'
    Game_Gear = 'Game Gear'
    Game_Boy = 'Game Boy'
    Game_Boy_Color = 'Game Boy Color'
    Game_Body_Advance = 'Game Body Advance'
    e_Reader = 'e-Reader'
    Game_Wave_Family_Entertainment_System = 'Game Wave Family Entertainment System'
    GameCube = 'GameCube'
    GameFly = 'GameFly'
    GamersGate = 'GamersGate'
    GameStop_PC = 'GameStop PC'
    Games_For_Windows = 'Games For Windows'
    Game_com = 'Game.com'
    Genesis_Mega_Drive = 'Genesis / Mega Drive'
    GetGames = 'GetGames'
    Gizmondo = 'Gizmondo'
    GOG_com = 'GOG.com'
    Google_Stadia = 'Google Stadia'
    GP2x_Wiz = 'GP2x Wiz'
    Green_Man_Gaming = 'Green Man Gaming'
    HTC_Vive = 'HTC Vive'
    Humble_Bundle_Store = 'Humble Bundle Store'
    HyperScan = 'HyperScan'
    IndieCity = 'IndieCity'
    IndieGala = 'IndieGala'
    Intellivision = 'Intellivision'
    Intellivision_Amico = 'Intellivision Amico'
    iOS = 'iOS'
    iPad = 'iPad'
    iPod = 'iPod'
    iPhone = 'iPhone'
    iQue_Player = 'iQue Player'
    itch_io = 'itch.io'
    Jaguar = 'Jaguar'
    Jaguar_CD = 'Jaguar CD'
    LaserActive = 'LaserActive'
    Linux = 'Linux'
    Lynx = 'Lynx'
    Mac = 'Mac'
    Magnavox_Odyssey = 'Magnavox Odyssey'
    Master_System = 'Master System'
    Microvision = 'Microvision'
    Miscellaneous = 'Miscellaneous'
    Mobile = 'Mobile'
    MSX = 'MSX'
    N_Gage = 'N-Gage'
    NEC_PC_6001 = 'NEC PC-6001'
    NEC_PC_6601 = 'NEC PC-6601'
    NEC_PC_8001 = 'NEC PC-8001'
    NEC_PC_8801 = 'NEC PC-8801'
    NEC_PC_9801 = 'NEC PC-9801'
    Neo_Geo = 'Neo Geo'
    Neo_Geo_CD = 'Neo Geo CD'
    Neo_Geo_Pocket_Color = 'Neo Geo Pocket Color'
    Nintendo_3DS = 'Nintendo 3DS'
    _3DS_Downloads = '3DS Downloads'
    Nintendo_DS = 'Nintendo DS'
    Nintendo_64 = 'Nintendo 64'
    Nintendo_64DD = 'Nintendo 64DD'
    Nintendo_Entertainment_System = 'Nintendo Entertainment System'
    Nintendo_Switch= 'Nintendo Switch'
    Switch_Downloads = 'Switch Downloads'
    Nuon = 'Nuon'
    Nuuvem = 'Nuuvem'
    Oculus_Store = 'Oculus Store'
    Odyssey2_Videopac = 'Odyssey2 Videopac'
    OnLive = 'OnLive'
    Origin = 'Origin'
    OUYA = 'OUYA'
    Pandora = 'Pandora'
    PC = 'PC'
    PICO_8 = 'PICO-8'
    Pinball = 'Pinball'
    Plato = 'Plato'
    Playdate = 'Playdate'
    Playdia = 'Playdia'
    PlayStation = 'PlayStation'
    PlayStation_2 = 'PlayStation 2'
    PlayStation_3 = 'PlayStation 3'
    PlayStation_4 = 'PlayStation 4'
    PlayStation_5 = 'PlayStation 5'
    PlayStation_Mobile = 'PlayStation Mobile'
    PlayStation_Network = 'PlayStation Network'
    PlayStation_Now = 'PlayStation Now'
    PSOne_Classics = 'PSOne Classics'
    PS2_Classics = 'PS2 Classics'
    PlayStation_minis = 'PlayStation minis'
    PlayStation_Portable = 'PlayStation Portable'
    PlayStation_Vita = 'PlayStation Vita'
    PlayStation_VR = 'PlayStation VR'
    PlayStation_VR2 = 'PlayStation VR2'
    Plug_and_Play = 'Plug-and-Play'
    PocketStation = 'PocketStation'
    Pokémon_Mini = 'Pokémon Mini'
    R_Zone = 'R-Zone'
    RCA_Studio_II = 'RCA Studio II'
    Rockstar_Games_Launcher = 'Rockstar Games Launcher'
    Super_A_Can = 'Super A Can'
    SAM_Coupé = 'SAM Coupé'
    Saturn = 'Saturn'
    Sega_CD = 'Sega CD'
    Sega_Pico = 'Sega Pico'
    Sega_SG_1000 = 'Sega SG-1000'
    SHARP_MZ_1500 = 'SHARP MZ-1500'
    Sharp_X1 = 'Sharp X1'
    Sharp_X68000 = 'Sharp X68000'
    Starpath_Supercharger = 'Starpath Supercharger'
    Steam = 'Steam'
    Super_Nintendo_Entertainment_System = 'Super Nintendo Entertainment System'
    SuperGrafx = 'SuperGrafx'
    Tapwave_Zodiac = 'Tapwave Zodiac'
    THhomas_MO5 = 'Thomas MO5'
    TI_99_4A = 'TI-99 4A'
    Tiger_Handhelds = 'Tiger Handhelds'
    TurboDuO = 'TurboDuo'
    TurboGrafx_16 = 'TurboGrafx-16'
    TurboGrafx_CD = 'TurboGrafx-CD'
    TRS_80_Color_Computer = 'TRS-80 Color Computer'
    Prime_Gaming = 'Prime Gaming'
    Uplay = 'Uplay'
    Vectrex = 'Vectrex'
    Virtual_Boy = 'Virtual Boy'
    Virtual_Console_Wii = 'Virtual Console Wii'
    Virtual_Console_3DS = 'Virtual Console 3DS'
    WASM_4 = 'WASM-4'
    Watara_Supervision = 'Watara Supervision'
    Wii = 'Wii'
    WiiWare = 'WiiWare'
    Wii_U = 'Wii U'
    Wii_U_Downalods = 'Wii U Downloads'
    Virtual_Console_Wii_U = 'Virtual Console Wii U'
    Windows_Phone_7 = 'Windows Phone 7'
    Windows_Store = 'Windows Store'
    WonderSwan_Color = 'WonderSwan Color'
    XaviXPORT = 'XaviXPORT'
    Xbox = 'Xbox'
    Xbox_360 = 'Xbox 360'
    Xbox_Game_Pass = 'Xbox Game Pass'
    Xbox_LIVE_Arcade = 'Xbox LIVE Arcade'
    XNA_Indie_Games = 'XNA Indie Games'
    Xbox_360_Game_on_Demand = 'Xbox 360 Games on Demand'
    Xbox_One ='Xbox One'
    Xbox_One_Downloads = 'Xbox One Downloads'
    Xbox_Series_X = 'Xbox Series X'
    Zeebo = 'Zeebo'
    Zune = 'Zune'
    ZX_Spectrum = 'ZX Spectrum'
    ZX_Soectrum_Next = 'ZX Spectrum Next'



class Region(Enum):
    NAM = 'NAM'
    JP= 'JP'
    PAL = 'PAL'
    CN = 'CN'
    KR= 'KR'
    BR = 'BR'
    OTHER = 'Other'

class Game(db.Model):
    __tablename__ = 'games'

    if environment == 'production':
        __table_args__ = {'schema': SCHEMA}

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    system = db.Column(db.Enum(System), nullable=False)
    region = db.Column(db.Enum(Region), nullable=False)

    #Relationships
    entries = db.relationship('Entry', back_populates='game_entries', cascade='all, delete-orphan')
    reviews = db.relationship('Review', back_populates='game_reviews', cascade='all, delete-orphan')



    def to_dict(self):
        return {
            'id': self.id,
            'name': self.name,
            'system': self.system.value,
            'region': self.region.value
        }
